### PR TITLE
Add macOS compatibility

### PR DESCRIPTION
**Pull request by superjeng1**
- Changed where to find `ChipInfoDb.dedicfg` file when built on macOS
- Allow longer path length

### CODE REVIEW

**Comment by superjeng1** [comment]
Using `#ifdef __linux__` and `#ifdef __APPLE__` compiler preprocessor to distinguish if the program is being built on Linux or Mac. This will not impact original functionality since the Linux code is untouched (except the increase of file path length).

**Review by Benwang217 — APPROVED** [review]

**Comment by superjeng1** [comment]
@Benwang217 Could you create a new release so this patch could be included in homebrew? Thanks!

**Comment by Benwang217** [comment]
Yes, I have released.

**Comment by superjeng1** [comment]
Thanks a lot!

**Pull request merged**
